"""init schema

Revision ID: 2b9a440b232f
Revises: 
Create Date: 2025-07-22 00:54:25.183371

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b9a440b232f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_id'), 'admin', ['id'], unique=False)
    op.create_index(op.f('ix_admin_username'), 'admin', ['username'], unique=True)
    op.create_table('donatur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('tempat_tinggal', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('no_telepon', sa.String(), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donatur_email'), 'donatur', ['email'], unique=True)
    op.create_index(op.f('ix_donatur_id'), 'donatur', ['id'], unique=False)
    op.create_index(op.f('ix_donatur_nama'), 'donatur', ['nama'], unique=False)
    op.create_index(op.f('ix_donatur_no_telepon'), 'donatur', ['no_telepon'], unique=True)
    op.create_table('penerima_donasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=True),
    sa.Column('penghasilan_perbulan', sa.Integer(), nullable=True),
    sa.Column('jumlah_tanggungan', sa.Integer(), nullable=True),
    sa.Column('status_tempat_tinggal', sa.String(), nullable=True),
    sa.Column('jumlah_kendaraan', sa.Integer(), nullable=True),
    sa.Column('jenis_kebutuhan', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_penerima_donasi_id'), 'penerima_donasi', ['id'], unique=False)
    op.create_index(op.f('ix_penerima_donasi_nama'), 'penerima_donasi', ['nama'], unique=False)
    op.create_table('barang_donasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('donatur_id', sa.Integer(), nullable=False),
    sa.Column('penerima_donasi_id', sa.Integer(), nullable=True),
    sa.Column('nama_barang', sa.String(), nullable=False),
    sa.Column('kategori', sa.String(), nullable=False),
    sa.Column('kondisi', sa.String(), nullable=False),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('tanggal_donasi', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['donatur_id'], ['donatur.id'], ),
    sa.ForeignKeyConstraint(['penerima_donasi_id'], ['penerima_donasi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_barang_donasi_donatur_id'), 'barang_donasi', ['donatur_id'], unique=False)
    op.create_index(op.f('ix_barang_donasi_id'), 'barang_donasi', ['id'], unique=False)
    op.create_index(op.f('ix_barang_donasi_penerima_donasi_id'), 'barang_donasi', ['penerima_donasi_id'], unique=False)
    op.create_table('barang_rekomendasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barang_id', sa.Integer(), nullable=True),
    sa.Column('penerima_id', sa.Integer(), nullable=True),
    sa.Column('layak', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['barang_id'], ['barang_donasi.id'], ),
    sa.ForeignKeyConstraint(['penerima_id'], ['penerima_donasi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barang_rekomendasi')
    op.drop_index(op.f('ix_barang_donasi_penerima_donasi_id'), table_name='barang_donasi')
    op.drop_index(op.f('ix_barang_donasi_id'), table_name='barang_donasi')
    op.drop_index(op.f('ix_barang_donasi_donatur_id'), table_name='barang_donasi')
    op.drop_table('barang_donasi')
    op.drop_index(op.f('ix_penerima_donasi_nama'), table_name='penerima_donasi')
    op.drop_index(op.f('ix_penerima_donasi_id'), table_name='penerima_donasi')
    op.drop_table('penerima_donasi')
    op.drop_index(op.f('ix_donatur_no_telepon'), table_name='donatur')
    op.drop_index(op.f('ix_donatur_nama'), table_name='donatur')
    op.drop_index(op.f('ix_donatur_id'), table_name='donatur')
    op.drop_index(op.f('ix_donatur_email'), table_name='donatur')
    op.drop_table('donatur')
    op.drop_index(op.f('ix_admin_username'), table_name='admin')
    op.drop_index(op.f('ix_admin_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
