"""init schema

Revision ID: 459a1d636bfc
Revises: 2b9a440b232f
Create Date: 2025-07-22 17:35:40.175122

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '459a1d636bfc'
down_revision: Union[str, Sequence[str], None] = '2b9a440b232f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('penerima_donasi', sa.Column('email', sa.String(), nullable=True))
    op.add_column('penerima_donasi', sa.Column('password_hash', sa.String(), nullable=False))
    op.create_index(op.f('ix_penerima_donasi_email'), 'penerima_donasi', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_penerima_donasi_email'), table_name='penerima_donasi')
    op.drop_column('penerima_donasi', 'password_hash')
    op.drop_column('penerima_donasi', 'email')
    # ### end Alembic commands ###
