"""tambahkan table hasilRekomendasi

Revision ID: 82f5fef36fed
Revises: e55b9d9d49fa
Create Date: 2025-08-19 17:11:46.177418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82f5fef36fed'
down_revision: Union[str, Sequence[str], None] = 'e55b9d9d49fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasilRekomendasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(), nullable=False),
    sa.Column('penghasilanPerbulan', sa.Integer(), nullable=False),
    sa.Column('jumlahTanggungan', sa.Integer(), nullable=False),
    sa.Column('statusTempatTinggal', sa.String(), nullable=False),
    sa.Column('jumlahKendaraan', sa.Integer(), nullable=False),
    sa.Column('jenisKebutuhan', sa.String(), nullable=False),
    sa.Column('layak', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('hasilrekomendasi')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hasilrekomendasi',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nama', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('penghasilan_perbulan', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('jumlah_tanggungan', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jumlah_kendaraan', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('jenis_kebutuhan', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status_tempat_tinggal', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('layak', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.CheckConstraint('layak = ANY (ARRAY[0, 1])', name=op.f('hasilrekomendasi_layak_check')),
    sa.PrimaryKeyConstraint('id', name=op.f('hasilrekomendasi_pkey'))
    )
    op.drop_table('hasilRekomendasi')
    # ### end Alembic commands ###
