"""menambahkan kolom password_hash di table Donatur

Revision ID: a31611298941
Revises: c29e20b44c7d
Create Date: 2025-07-22 17:45:42.628369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a31611298941'
down_revision: Union[str, Sequence[str], None] = 'c29e20b44c7d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donatur', sa.Column('password_hash', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donatur', 'password_hash')
    # ### end Alembic commands ###
