"""menambahkan email dan password_hash di table penerima donasi 

Revision ID: c29e20b44c7d
Revises: 459a1d636bfc
Create Date: 2025-07-22 17:41:13.854657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c29e20b44c7d'
down_revision: Union[str, Sequence[str], None] = '459a1d636bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
