"""merubah kolom password_hash jadi password

Revision ID: e55b9d9d49fa
Revises: 24e2ec4579b4
Create Date: 2025-07-24 18:46:12.283424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e55b9d9d49fa'
down_revision: Union[str, Sequence[str], None] = '24e2ec4579b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('admin', 'password_hash')
    op.add_column('donatur', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('donatur', 'password_hash')
    op.add_column('penerima_donasi', sa.Column('password', sa.String(), nullable=False))
    op.drop_column('penerima_donasi', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('penerima_donasi', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('penerima_donasi', 'password')
    op.add_column('donatur', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('donatur', 'password')
    op.add_column('admin', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('admin', 'password')
    # ### end Alembic commands ###
