name: Python Application CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout kode
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Setup Python versi 3.10
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    # 3. Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Jalankan tes
    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -q

    # 5. Pastikan .env tidak terbawa
    - name: Verify .env is ignored
      run: |
        if [ -f ".env" ]; then
          echo ".env file exists locally, but should not be committed."
        fi
